# Edits of this spec should be validated using https://editor.swagger.io/
# TODO:
# - Error responses

openapi: 3.0.0
info:
  title: Som Energia Open Data API
  version: 0.2.25
  license:
    name: GNU Affero General Public License
    url: http://www.gnu.org/licenses/agpl-3.0.en.html
  description: |
    This API can be used to obtain metrics
    about [Som Energia](https://somenergia.coop)
    and several related visualizations and widgets.

    Source metric measurements are obtained
    at **the start** of every **first of month**
    with **city granularity**.
    That is the smaller resolution this API provides: month and city.
    Coarser resolutions in time and space
    are obtained **by aggregation** of those source measurements.

    Because the measurement for a day is obtained at the begining of that day,
    a value for 2020-01-01 will include events up to the end of 2019 but none from 2020.
    Likewise,
    a value for 2020-02-01 will include events up to the end of January but none about February.

    Be aware that each metric has particular considerations about its meaning and reliability.
    They are included in the metric description,
    retrievable by means of the discovery API.

    Glossary:

    - **Metric:** Something to be measured
    - **Relative metric:** Something available to relativize metrics
      (population, surface, existing supply points, overall energy consumption...)
    - **Geolevel:** A geographical partition: country, state, city...
    - **Region:** Each of the elements of the geolevel.
      For instance, at country geolevel we have as regions Spain, France...

servers:
  - url: https://opendata.somenergia.coop/v0.2
    description: Production server
  - url: http://localhost:5001/v0.2
    description: Development server

tags:
- name: About
  description: Information about the running API
- name: Discovery
  description: "Discovering the evolving elements of the API: metrics, geolevels..."
- name: Numeric data
  description: Obtaining processable numeric data
- name: Maps
  description: Generate geographical distribution maps for the metrics

paths:

  /version:
    get:
      summary: API version
      description: Returns current and oldest backward compatible versions
      tags: [ About ]
      parameters:
      - $ref: '#/components/parameters/query_format_yaml_json'
      responses:
        '200':
          description: Version information
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/VersionInfo'
              example:
                version: '0.2.25'
                compat: '0.2.1'
            application/yaml:
              schema:
                $ref: '#/components/schemas/VersionInfo'
              example:
                version: '0.2.25'
                compat: '0.2.1'

  /spec:
    get:
      summary: API specification
      description: API specification using OpenAPI 3.0 in YAML format.
      tags: [ About ]
      response:
        '200':
          application/yaml:
            type: object

  /discover/metrics:
    get:
      summary: Available metrics
      tags: [ Discovery ]
      parameters:
      - $ref: '#/components/parameters/query_lang'
      - $ref: '#/components/parameters/query_format_yaml_json'
      responses:
        '200':
          description: Returns the list of available metrics
          content:
            application/yaml:
              schema:
                $ref: '#/components/schemas/MetricsInfo'
              example:
                metrics:
                - id: members
                  text: 'Members'
                  description: "Members of the cooperative at the end of the day."
                - id: contracts
                  text: 'Contracts'
                  description: "Active contracts at the end of the day."
            application/json:
              schema:
                $ref: '#/components/schemas/MetricsInfo'
              example:
                metrics:
                - id: members
                  text: 'Members'
                  description: "Members of the cooperative at the end of the day."
                - id: contracts
                  text: 'Contracts'
                  description: "Active contracts at the end of the day."

  /discover/geolevel:
    get:
      summary: Available geolevels
      description: Returns the geolevels (short for geographical levels) that can be used in queries. For example, countries, cities...
      tags: [ Discovery ]
      parameters:
      - $ref: '#/components/parameters/query_lang'
      - $ref: '#/components/parameters/query_format_yaml_json'
      responses:
        '200':
          description: A list of available geolevels
          content:
            application/yaml:
              schema:
                $ref: '#/components/schemas/GeolevelsInfo'
              example:
                geolevels:
                - id: world
                  text: 'World'
                  mapable: False
                - id: country
                  text: 'Country'
                  parent: world
                  plural: countries
                  mapable: False
                - id: ccaa
                  text: 'Autonomous Community'
                  parent: country
                  plural: ccaas
                - id: state
                  text: 'State'
                  parent: ccaa
                  plural: states
                - id: city
                  text: 'City'
                  parent: state
                  plural: cities
                  mapable: False
                - id: localgroup
                  text: 'Local Group'
                  parent: world
                  plural: localgroups
                  detailed: False
                  mapable: False

            application/json:
              schema:
                $ref: '#/components/schemas/GeolevelsInfo'
              example:
                geolevels:
                - id: world
                  text: 'World'
                  mapable: False
                - id: country
                  text: 'Country'
                  parent: world
                  plural: countries
                  mapable: False
                - id: ccaa
                  text: 'Autonomous Community'
                  parent: country
                  plural: ccaas
                - id: state
                  text: 'State'
                  parent: ccaa
                  plural: states
                - id: city
                  text: 'City'
                  parent: state
                  plural: cities
                  mapable: False
                - id: localgroup
                  text: 'Local Group'
                  parent: world
                  plural: localgroups
                  detailed: False
                  mapable: False

  /discover/geolevel/{geolevel}:
    get:
      summary: Available geolevels values
      description: >
        Returns the available values for a given geographical division.
      tags: [ Discovery ]
      parameters:
      - $ref: '#/components/parameters/path_geolevelOrAlias'
      - $ref: '#/components/parameters/geofilter_city'
      - $ref: '#/components/parameters/geofilter_state'
      - $ref: '#/components/parameters/geofilter_ccaa'
      - $ref: '#/components/parameters/geofilter_country'
      - $ref: '#/components/parameters/geofilter_gl'
      - $ref: '#/components/parameters/query_lang'
      - $ref: '#/components/parameters/query_format_yaml_json'
      responses:
        '200':
          description: A list of available geolevels
          content:
            application/yaml:
              schema:
                $ref: '#/components/schemas/GeolevelValues'
              examples:
                ccaas:
                  summary: /discover/geolevel/ccaa?lang=es
                  description: All the CCAA's. Force name translation to Spanish instead of using the browser language.
                  value:
                    options:
                      '01': Andalucia
                      '02': Aragón
                      '03': Asturias, Principado de
                      '04': Baleares, Islas
                      '05': Canarias
                      '06': Cantabria
                      '07': Castilla y León
                      '08': Castilla - La Mancha
                      '09': Cataluña
                      '10': Comunidad Valenciana
                      '11': Extremadura
                      '12': Galicia
                      '13': Madrid, Comunidad de
                      '14': Murcia, Región de
                      '15': Navarra, Comunidad Foral de
                      '16': País Vasco
                      '17': Rioja, La
                localgroupsccaa:
                  summary: "/discover/geolevel/localgroup?ccaa=09"
                  description: All local groups in Catalonia Autonomous Community (INE code 09)
                  value:
                    options:
                      AltPenedes: Alt Penedès
                      Anoia: Anoia
                      Badalona: Badalona
                      Bages: Bages
                      BaixLlobregat: Baix Llobregat
                      BaixMontseny: Baix Montseny
                      BaixValles: Baix Vallès
                      Barcelona: Barcelona
                      CastellarValles: Castellar del Vallès
                      CerdanyolaValles: Cerdanyola del Vallès
                      Maresme: Maresme
                      Osona: Osona
                      Rubi: Rubí
                      Sabadell: Sabadell
                      SantCugatValles: Sant Cugat del Vallès
                      SelvaMaritima: Selva Marítima
                      Terrassa: Terrassa


  /{metric}/by/{geolevel}/on/{ondate}:
    get:
      summary: Metric data on a given date
      description: |
        Returns the metric
        computed with the given geographical level of detail
        on a given date.

        Geographical fliters in the query string
        restrict the regions to be considered.
        Filters are additive, a city, the lowest level of detail,
        is incorporated if it matches any provided filter.

        Elidible parts:

        - `/by/{geolevel}`: when omited means `world`
        - `/on/{date}`: when omitted means the latest available date

        Some examples:

        - `/contracts`
          - Current number of contracts:
        - `/members/by/state`
          - Current members at every state:
        - `/members/by/ccaa/on/2018-02-01`
          - Members at every CCAA on 2018-02-01:
        - `/members/by/city?state=01&state=20`
          - Members by city on Araba and Gipuzcoa provinces:

      tags: [ "Numeric data" ]
      parameters:

      - $ref: '#/components/parameters/path_metric'
      - $ref: '#/components/parameters/path_geolevel'
      - $ref: '#/components/parameters/path_onDate'
      - $ref: '#/components/parameters/query_lang'
      - $ref: '#/components/parameters/query_format_yaml_json_tsv'
      - $ref: '#/components/parameters/geofilter_city'
      - $ref: '#/components/parameters/geofilter_state'
      - $ref: '#/components/parameters/geofilter_ccaa'
      - $ref: '#/components/parameters/geofilter_country'
      - $ref: '#/components/parameters/geofilter_gl'
      responses:
        '200':
          description: Successful response
          content:
            application/yaml:
              schema:
                $ref: '#/components/schemas/MultiLevelNumbers'
              examples:
                membersByCCAA:
                  summary: /members/by/ccaa/on/2013-01-01
                  description: |
                    Members detailed by CCAA on 2013-01-01
                  value:
                    dates:
                    - 2013-01-01
                    values:
                    - 3197
                    countries:
                      ES:
                        name: España
                        values:
                        - 3197
                        ccaas:
                          '01':
                            name: Andalucia
                            values:
                            - 48
                          '02':
                            name: Aragón
                            values:
                            - 124
                          '03':
                            name: Asturias, Principado de
                            values:
                            - 13
                          '04':
                            name: Baleares, Islas
                            values:
                            - 235
                          '05':
                            name: Canarias
                            values:
                            - 0
                          '06':
                            name: Cantabria
                            values:
                            - 12
                          08:
                            name: Castilla - La Mancha
                            values:
                            - 28
                          '07':
                            name: Castilla y León
                            values:
                            - 24
                          09:
                            name: Cataluña
                            values:
                            - 2054
                          '10':
                            name: Comunidad Valenciana
                            values:
                            - 224
                          '11':
                            name: Extremadura
                            values:
                            - 14
                          '12':
                            name: Galicia
                            values:
                            - 24
                          '13':
                            name: Madrid, Comunidad de
                            values:
                            - 145
                          '14':
                            name: Murcia, Región de
                            values:
                            - 11
                          '15':
                            name: Navarra, Comunidad Foral de
                            values:
                            - 151
                          '16':
                            name: País Vasco
                            values:
                            - 53
                          '17':
                            name: Rioja, La
                            values:
                            - 37
            text/tab-separated-values:
              schema:
                type: text
              examples:
                tsvcitydetail:
                  summary: /members/by/city/on/2012-01-01/?city=08089&format=tsv
                  description: |
                    Members in Gavà at the begining of 2012 using tsv format
                  value:
                    "country_code\tcountry\tccaa_code\tccaa\tstate_code\tstate\tcity_code\tcity\t2012-01-01\n\
                     ES\tEspaña\t09\tCatalunya\t08\tBarcelona\t08089\tGavà\t32\n\
                     "
                tsvccaadetail:
                  summary: /members/by/state/on/2012-01-01/?ccaa=09&format=tsv
                  description: |
                    Members in Catalonia by state at the begining of 2012 using tsv format
                  value:
                    "country_code\tcountry\tccaa_code\tccaa\tstate_code\tstate\t2012-01-01\n\
                     ES\tEspaña\t09\tCataluña\t08\tBarcelona\t80\n\
                     ES\tEspaña\t09\tCataluña\t17\tGirona\t15\n\
                     ES\tEspaña\t09\tCataluña\t25\tLleida\t5\n\
                     ES\tEspaña\t09\tCataluña\t43\tTarragona\t2\n\
                     "


  /{metric}/by/{geolevel}/{frequency}/from/{fromdate}/to/{todate}:
    get:
      summary: Metric data on in a series of dates
      description: |
        Returns the metric
        computed with the given geographical level of detail
        for a series of dates.

        Geographical fliters in the query string
        restrict the regions to be considered.
        Filters are additive, a city, the lowest level of detail,
        is incorporated if it matches any provided filter.

        Use the filters in the query string to restrict to a group of geographical entities.
        The filters are additive. That means that any city matching any of the specified values will be counted.

        Elidible parts:

        - `/by/{geolevel}`: when omited means `world`
        - `/from/{date}`: when omitted means the first available date
        - `/to/{date}`: when omitted means the latest available date

        Some examples:

        - `/contracts/yearly`
          - Evolution of all contracts every year
        - `/members/monthly/from/2018-01-01/to/2019-01-01`
          - Monthly evolution of members during 2018
        - `/members/by/city/yearly/from/2018-01-01?state=01&state=20`
          - Members by city on Araba (01) and Gipuzcoa (20) provinces every year since 2018


      tags: [ "Numeric data" ]
      parameters:

      - $ref: '#/components/parameters/path_metric'
      - $ref: '#/components/parameters/path_geolevel'
      - $ref: '#/components/parameters/path_periodicity'
      - $ref: '#/components/parameters/path_fromDate'
      - $ref: '#/components/parameters/path_toDate'
      - $ref: '#/components/parameters/query_lang'
      - $ref: '#/components/parameters/query_format_yaml_json_tsv'
      - $ref: '#/components/parameters/geofilter_city'
      - $ref: '#/components/parameters/geofilter_state'
      - $ref: '#/components/parameters/geofilter_ccaa'
      - $ref: '#/components/parameters/geofilter_country'
      - $ref: '#/components/parameters/geofilter_gl'
      responses:
        '200':
          description: Successful response
          content:
            application/yaml:
              schema:
                $ref: '#/components/schemas/MultiLevelNumbers'
              examples:
                membersByCCAA:
                  summary: /members/by/ccaa/yearly/from/2010-01-01/to/2013-01-01
                  description: |
                    Members detailed by CCAA, evolution from 2010-01-01 2010-01-01 yearly
                  value:
                    dates:
                    - 2010-01-01
                    - 2011-01-01
                    - 2012-01-01
                    - 2013-01-01
                    values:
                    - 0
                    - 0
                    - 277
                    - 3197
                    countries:
                    ES:
                        name: España
                        values:
                        - 0
                        - 0
                        - 277
                        - 3197
                        ccaas:
                        '01':
                            name: Andalucia
                            values:
                            - 0
                            - 0
                            - 0
                            - 48
                        '02':
                            name: Aragón
                            values:
                            - 0
                            - 0
                            - 0
                            - 124
                        '03':
                            name: Asturias, Principado de
                            values:
                            - 0
                            - 0
                            - 0
                            - 13
                        '04':
                            name: Baleares, Islas
                            values:
                            - 0
                            - 0
                            - 1
                            - 235
                        '05':
                            name: Canarias
                            values:
                            - 0
                            - 0
                            - 0
                            - 0
                        '06':
                            name: Cantabria
                            values:
                            - 0
                            - 0
                            - 0
                            - 12
                        08:
                            name: Castilla - La Mancha
                            values:
                            - 0
                            - 0
                            - 0
                            - 28
                        '07':
                            name: Castilla y León
                            values:
                            - 0
                            - 0
                            - 0
                            - 24
                        09:
                            name: Cataluña
                            values:
                            - 0
                            - 0
                            - 256
                            - 2054
                        '10':
                            name: Comunidad Valenciana
                            values:
                            - 0
                            - 0
                            - 11
                            - 224
                        '11':
                            name: Extremadura
                            values:
                            - 0
                            - 0
                            - 0
                            - 14
                        '12':
                            name: Galicia
                            values:
                            - 0
                            - 0
                            - 0
                            - 24
                        '13':
                            name: Madrid, Comunidad de
                            values:
                            - 0
                            - 0
                            - 3
                            - 145
                        '14':
                            name: Murcia, Región de
                            values:
                            - 0
                            - 0
                            - 0
                            - 11
                        '15':
                            name: Navarra, Comunidad Foral de
                            values:
                            - 0
                            - 0
                            - 6
                            - 151
                        '16':
                            name: País Vasco
                            values:
                            - 0
                            - 0
                            - 0
                            - 53
                        '17':
                            name: Rioja, La
                            values:
                            - 0
                            - 0
                            - 0
                            - 37
            text/tab-separated-values:
              schema:
                type: text
              examples:
                tsvseriescitydetail:
                  summary: /members/by/city/yearly/from/2012-01-01/to/2013-01-01/?city=08089&format=tsv
                  description: |
                    Members in Gavà from 2012 to 2013 in tsv format

                    Succesive dates are added as columns
                  value:
                    "country_code\tcountry\tccaa_code\tccaa\tstate_code\tstate\tcity_code\tcity\t2012-01-01\t2013-01-01\n\
                     ES\tEspaña\t09\tCatalunya\t08\tBarcelona\t08089\tGavà\t232\t478\n"
                tsvseriesccaadetail:
                  summary: /members/by/state/yearly/from/2012-01-01/to/2013-01-01?ccaa=09&format=tsv
                  description: |
                    Members in Catalonia by state from 2012 to 2013 using tsv format
                  value:
                    "country_code\tcountry\tccaa_code\tccaa\tstate_code\tstate\t2012-01-01\n\
                     ES\tEspaña\t09\tCataluña\t08\tBarcelona\t80\t120\n\
                     ES\tEspaña\t09\tCataluña\t17\tGirona\t15\t21\n\
                     ES\tEspaña\t09\tCataluña\t25\tLleida\t5\t12\n\
                     ES\tEspaña\t09\tCataluña\t43\tTarragona\t2\t11\n\
                     "

  /map/{metric}/by/{geolevel}/on/{ondate}:
    get:
      summary: Absolute metric map
      description: |
        Returns a map representing the geographical distribution
        of the metric on a given date.

        Use the geolevel choose the map detail (ccaa, state).

        Elidible parts:

        - `/by/{geolevel}`: when omited means `ccaa` (Not world!)
        - `/on/{date}`: when omitted means the latest available date

        [Experimental] You can specify the extent of the map,
        by default `country=ES`. It will work if a map template
        for the combination of extent and geolevel exists.

        Examples:

        - `/map/contracts`
          - Current number of contracts by ccaa
        - `/map/members/by/state`
          - Current members at every state
        - `/map/members/by/ccaa/on/2018-02-01`
          - Members at every CCAA on 2018-02-01
        - `/map/members/by/city?localgroup=BaixMontseny`
          - Current members at every city of Baix Montseny localgroup

      tags: [ "Maps" ]
      parameters:

      - $ref: '#/components/parameters/path_metric'
      - $ref: '#/components/parameters/path_mapgeolevel'
      - $ref: '#/components/parameters/path_onDate'
      - $ref: '#/components/parameters/mapextent_country'
      - $ref: '#/components/parameters/mapextent_gl'
      - $ref: '#/components/parameters/query_lang'
      responses:
        '200':
          description: SVG map
          content:
            image/svg+xml:
              schema:
                type: string

  /map/{metric}/per/{relativemetric}/by/{geolevel}/on/{ondate}:
    get:
      summary: Relative metric map
      description: |
        Returns a map representing the geographical distribution at a given date
        of the metric relative to a reference metric (population).

        Elidible parts:

        - `/by/{geolevel}`: when omited means `ccaa` (Not world!)
        - `/from/{date}`: when omitted means the first available date
        - `/to/{date}`: when omitted means the latest available date

        [Experimental] You can specify the extent of the map,
        by default `country=ES`. It will work if a map template
        for the combination of extent and geolevel exists.

      tags: [ "Maps" ]
      parameters:

      - $ref: '#/components/parameters/path_metric'
      - $ref: '#/components/parameters/path_relativemetric'
      - $ref: '#/components/parameters/path_mapgeolevel'
      - $ref: '#/components/parameters/path_onDate'
      - $ref: '#/components/parameters/mapextent_country'
      - $ref: '#/components/parameters/mapextent_gl'
      - $ref: '#/components/parameters/query_lang'
      responses:
        '200':
          description: SVG map
          content:
            image/svg+xml:
              schema:
                type: string

  /map/{metric}/by/{geolevel}/{frequency}/from/{fromdate}/to/{todate}:
    get:
      summary: Absolute metric map animation
      description: |
        Returns an animated map of the evolving geographical distribution
        for a serie of dates of the metric.

        Use the geolevel choose the map detail (ccaa, state).

        Elidible parts:

        - `/by/{geolevel}`: when omited means `ccaa` (Not world!)
        - `/from/{date}`: when omitted means the first available date
        - `/to/{date}`: when omitted means the latest available date

        [Experimental] You can specify the extent of the map,
        by default `country=ES`. It will work if a map template
        for the combination of extent and geolevel exists.

      tags: [ "Maps" ]
      parameters:
      - $ref: '#/components/parameters/path_metric'
      - $ref: '#/components/parameters/path_mapgeolevel'
      - $ref: '#/components/parameters/path_periodicity'
      - $ref: '#/components/parameters/path_fromDate'
      - $ref: '#/components/parameters/path_toDate'
      - $ref: '#/components/parameters/mapextent_country'
      - $ref: '#/components/parameters/mapextent_gl'
      - $ref: '#/components/parameters/query_lang'
      responses:
        '200':
          description: Animated SVG map
          content:
            image/svg+xml:
              schema:
                type: string

  /map/{metric}/per/{relativemetric}/by/{geolevel}/{frequency}/from/{fromdate}/to/{todate}:
    get:
      summary: Relative metric map animation
      description: |
        Returns an animated map of the evolving geographical distribution
        for a serie of dates of the metric relative to the reference metric.

        Use the geolevel choose the map detail (ccaa, state).

        Elidible parts:

        - `/by/{geolevel}`: when omited means `ccaa` (Not world!)
        - `/from/{date}`: when omitted means the first available date
        - `/to/{date}`: when omitted means the latest available date

        [Experimental] You can specify the extent of the map,
        by default `country=ES`. It will work if a map template
        for the combination of extent and geolevel exists.

      tags: [ "Maps" ]
      parameters:
      - $ref: '#/components/parameters/path_metric'
      - $ref: '#/components/parameters/path_relativemetric'
      - $ref: '#/components/parameters/path_mapgeolevel'
      - $ref: '#/components/parameters/path_periodicity'
      - $ref: '#/components/parameters/path_fromDate'
      - $ref: '#/components/parameters/path_toDate'
      - $ref: '#/components/parameters/mapextent_country'
      - $ref: '#/components/parameters/mapextent_gl'
      - $ref: '#/components/parameters/query_lang'
      responses:
        '200':
          description: Animated SVG map
          content:
            image/svg+xml:
              schema:
                type: string


components:
  parameters:
    query_lang:
      name: lang
      in: query
      required: false
      description: |
        Language to force for translated texts.
        If no language is forced, the one in the browser (Accepted-Language header) is taken.
        If the languange is not one of the supported ones, english is taken by default.
      schema:
        type: string
        nullable: true
        enum:
        - ca
        - gl
        - eu
        - es
        - en
        - null

    query_format_yaml_json_tsv:
      name: format
      in: query
      required: false
      description:
        Format for the result (yaml, json, tsv). yaml if not (properly) specified.
      schema:
        type: string
        nullable: true
        enum:
        - tsv
        - yaml
        - json
        - null

    query_format_yaml_json:
      name: format
      in: query
      required: false
      description:
        Format for the result (yaml, json). yaml if not (properly) specified.
      schema:
        type: string
        nullable: true
        enum:
        - json
        - yaml
        - null

    path_metric:
      name: metric
      in: path
      required: true
      description: |
        The code of a supported metric (see /discover/metrics)
      schema:
        type: string
        pattern: '[a-z][a-z0-9]+'
        enum:
        - contracts
        - members
        - selfconsumptioncontracts
        - newcontracts
        - newmembers
        - newselfconsumptioncontracts
        - canceledcontracts
        - canceledmembers
        - canceledselfconsumptioncontracts

    path_relativemetric:
      name: relativemetric
      in: path
      required: true
      description: |
        One of the supported metrics to relativize main metrics. (By now just `population`)
      schema:
        type: string
        pattern: '[a-z][a-z0-9]+'
        enum:
        - population

    path_geolevel:
      name: geolevel
      in: path
      description: |
        Geographical level of detail.
        Use the golevel to get mor geographical detail (country, ccaa, state, city).
        For just the global numbers, remove the whole `/by/{geolevel}` portion of the path.
      required: true
      schema:
        type: string
        pattern: '[a-z][a-z0-9]+'
        default: null
        nullable: true
        enum:
        - country
        - ccaa
        - state
        - city
        - null

    path_mapgeolevel:
      name: geolevel
      in: path
      description: |
        Geographical level of detail.
        Use the golevel to get mor geographical detail (ccaa, state).
      required: true
      schema:
        type: string
        pattern: '[a-z][a-z0-9]+'
        enum:
        - ccaa
        - state
        - city

    path_geolevelOrAlias:
      name: geolevel
      in: path
      description: |
        Geographical detail level, including aliased geolevel alias, like localgroup.
      required: true
      schema:
        type: string
        pattern: '[a-z][a-z0-9]+'
        enum:
        - country
        - ccaa
        - state
        - city
        - localgroup

    path_periodicity:
      name: frequency
      required: true
      description: |
        Indicate a date sequence (only first day of the month, year...)
      in: path
      schema:
        type: string
        enum:
        - monthly
        - yearly

    path_onDate:
      name: ondate
      required: true
      description: |
        Single date, in ISO format (YYYY-MM-DD).
        To obtain the last available data, remove the whole `/on/:onDate` portion of the path.
      in: path
      schema:
        type: string
        format: date

    path_fromDate:
      name: fromdate
      required: true
      description: |
        Earlier date to show, in iso format (YYYY-MM-DD).
        To set it to the first date available data, remove the whole `/from/{fromdate}` portion of the path.
      in: path
      schema:
        type: string
        format: date

    path_toDate:
      name: todate
      required: true
      description: |
        Later date to show, in iso format (YYYY-MM-DD).
        To set it to the last date available data, remove the whole `/to/{todate}` portion of the path.
      in: path
      schema:
        type: string
        format: date

    geofilter_city:
      description: INE codes of cities to be included
      name: city
      in: query
      explode: true
      schema:
        $ref: '#/components/schemas/CodeArray'

    geofilter_state:
      description: INE codes of states to be included
      name: state
      in: query
      explode: true
      schema:
        $ref: '#/components/schemas/CodeArray'

    geofilter_ccaa:
      description: INE codes of CCAAs to be included
      name: ccaa
      in: query
      explode: true
      schema:
        $ref: '#/components/schemas/CodeArray'

    geofilter_country:
      description: ISO codes of countries to be included
      name: country
      in: query
      explode: true
      schema:
        $ref: '#/components/schemas/CodeArray'

    geofilter_gl:
      description: Codes of the local groups to be included
      name: localgroup
      in: query
      explode: true
      schema:
        $ref: '#/components/schemas/CodeArray'

    mapextent_country:
      description: |
        (Experimental) Set the extent of the map to the country

        This parameter is incompatible with other extent parameters.

        Available value `ES` (the default if no other extent is specified)
        with `state` or `ccaa` geolevels.
      name: country
      in: query
      schema:
        $ref: '#/components/schemas/GeoCode'

    mapextent_gl:
      description: |
        (Experimental) Set the extent of the map to the local group.

        This parameter is incompatible with other extent parameters.

        Available values `BaixMontseny` and `BaixLlobregat`
        with `city` geolevel.
      name: localgroup
      in: query
      schema:
        $ref: '#/components/schemas/GeoCode'

  schemas:

    VersionInfo:
      type: object
      properties:
        version:
          type: string
          description: Current API version
          example: 0.2.25
        compat:
          type: string
          description: Oldest backward compatible version
          example: 0.2.1

    MetricsInfo:
      type: object
      required: [metrics]
      properties:
        metrics:
          type: array
          items:
            type: object
            properties:
              name:
                type: string
                pattern: '[a-z][a-z0-9]+'
                description: Identifier name used to refer the metric
              text:
                type: string
                description: Translated text name to be shown to the user to refer the metric
              description:
                type: string
                format: CommonMark
                description: Translated Markdown text describing the metric


    GeolevelsInfo:
      type: object
      properties:
        geolevels:
          type: array
          items:
            type: object
            properties:
              id:
                type: string
                pattern: '[a-z][a-z0-9]+'
                description: Identifier name used to refer the geolevel
              text:
                type: string
                description: Translated text name to be shown to the user to refer the geolevel
              description:
                type: string
                format: CommonMark
                description: Translated Markdown text describing the metric
              plural:
                type: string
                pattern: '[a-z][a-z0-9]+'
                default: id + 's'
                description: Plural tag to use in structures
              parent:
                type: string
                pattern: '[a-z][a-z0-9]+'
                description: The parent geolevel id
                default: null
              detailed:
                type: boolean
                default: True
                description: Set to false if it is not supported as level of detail for distributions
              mapable:
                type: boolean
                default: True
                description: Set to false if it is not supported as level of detail for map

    GeolevelValues:
      description: A list of regions at the specified geolevel
      type: object
      properties:
        options:
          type: object
          additionalProperties:
            type: string
            description: Translated name of the geolevel region
          description: Map from geolevel region code to its translated name

    CodeArray:
      type: array
      items:
        $ref: '#/components/schemas/GeoCode'

    GeoCode:
      type: string
      pattern: '[a-zA-Z0-9]+'

    NumbersSublevel:
      type: object
      properties:
        name:
          description: Translated name for the region
          type: string
        values:
          description: Metric value for each date, aggregated for the region
          type: array
          items:
            type: number

    Countries:
      description: A map of country codes to the details of each country
      type: object
      additionalProperties:
        allOf:
        - $ref: '#/components/schemas/NumbersSublevel'
        - type: object
          properties:
            ccaas:
              $ref: '#/components/schemas/CCAAs'

    CCAAs:
      description: A map of CCAA INE codes to the CCAA detailed values
      type: object
      additionalProperties:
        allOf:
        - $ref: '#/components/schemas/NumbersSublevel'
        - type: object
          properties:
            states:
              $ref: '#/components/schemas/States'

    States:
      description: A map of State INE codes to the state detailed values
      type: object
      additionalProperties:
        allOf:
        - $ref: '#/components/schemas/NumbersSublevel'
        - type: object
          properties:
            cities:
              $ref: '#/components/schemas/Cities'

    Cities:
      description: A map of city INE codes to the city detailed values
      type: object
      additionalProperties:
        $ref: '#/components/schemas/NumbersSublevel'

    MultiLevelNumbers:
      description: Structured numeric information
      type: object
      properties:
        dates:
          description: sorted list of dates at which metric is computed
          type: array
          items:
            type: string
            format: Dates
        values:
          description: A list of metric values globally aggregated for each date
          type: array
          items:
            type: number
        countries:
          $ref: '#/components/schemas/Countries'
      required:
      - dates
      - values

# vim: et ts=2 sw=2
